// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinGameRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId               string   `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	JoinAsDealer         bool     `protobuf:"varint,3,opt,name=joinAsDealer,proto3" json:"joinAsDealer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGameRequest) Reset()         { *m = JoinGameRequest{} }
func (m *JoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGameRequest) ProtoMessage()    {}
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *JoinGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameRequest.Unmarshal(m, b)
}
func (m *JoinGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameRequest.Marshal(b, m, deterministic)
}
func (m *JoinGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameRequest.Merge(m, src)
}
func (m *JoinGameRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGameRequest.Size(m)
}
func (m *JoinGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameRequest proto.InternalMessageInfo

func (m *JoinGameRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *JoinGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *JoinGameRequest) GetJoinAsDealer() bool {
	if m != nil {
		return m.JoinAsDealer
	}
	return false
}

type JoinGameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGameResponse) Reset()         { *m = JoinGameResponse{} }
func (m *JoinGameResponse) String() string { return proto.CompactTextString(m) }
func (*JoinGameResponse) ProtoMessage()    {}
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *JoinGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGameResponse.Unmarshal(m, b)
}
func (m *JoinGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGameResponse.Marshal(b, m, deterministic)
}
func (m *JoinGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGameResponse.Merge(m, src)
}
func (m *JoinGameResponse) XXX_Size() int {
	return xxx_messageInfo_JoinGameResponse.Size(m)
}
func (m *JoinGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGameResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JoinGameRequest)(nil), "rpc.JoinGameRequest")
	proto.RegisterType((*JoinGameResponse)(nil), "rpc.JoinGameResponse")
}

func init() {
	proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6)
}

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0xca, 0xe6,
	0xe2, 0xf7, 0xca, 0xcf, 0xcc, 0x73, 0x4f, 0xcc, 0x4d, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x92, 0xe6, 0xe2, 0x84, 0xa8, 0x8b, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0xe2, 0x80, 0x08, 0x78, 0xa6, 0x08, 0x89, 0x73, 0xb1, 0xa7, 0x27, 0xe6, 0xa6, 0x82, 0xa4, 0x98,
	0xc0, 0x52, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x12, 0x17, 0x4f, 0x56, 0x7e, 0x66, 0x9e, 0x63,
	0xb1, 0x4b, 0x6a, 0x62, 0x4e, 0x6a, 0x91, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x8a, 0x98,
	0x92, 0x10, 0x97, 0x00, 0xc2, 0xb2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x23, 0x47, 0x2e, 0xb6,
	0x00, 0xb0, 0xe1, 0x42, 0xe6, 0x5c, 0x1c, 0x30, 0x59, 0x21, 0x11, 0xbd, 0xa2, 0x82, 0x64, 0x3d,
	0x34, 0x97, 0x49, 0x89, 0xa2, 0x89, 0x42, 0x8c, 0x48, 0x62, 0x03, 0xfb, 0xc7, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x83, 0x1e, 0x3c, 0x60, 0xdf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error)
}

type playerClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerClient(cc grpc.ClientConnInterface) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) JoinGame(ctx context.Context, in *JoinGameRequest, opts ...grpc.CallOption) (*JoinGameResponse, error) {
	out := new(JoinGameResponse)
	err := c.cc.Invoke(ctx, "/rpc.Player/JoinGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	JoinGame(context.Context, *JoinGameRequest) (*JoinGameResponse, error)
}

// UnimplementedPlayerServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServer struct {
}

func (*UnimplementedPlayerServer) JoinGame(ctx context.Context, req *JoinGameRequest) (*JoinGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Player/JoinGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).JoinGame(ctx, req.(*JoinGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinGame",
			Handler:    _Player_JoinGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
